### PR TITLE
rustup for latest nightly

### PR DESCRIPTION
**Pull request by aidanhs**

### CODE REVIEW

**Comment by Manishearth** [comment]
The test seems to fail

**Comment by aidanhs** [comment]
Pushed fixed version, tests passed.

**Comment by aidanhs** [comment]
Updated PR to work on lastest nightly. Not sure what the test failures are about:
```
  = note: /usr/bin/ld: /home/travis/rust/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1357b93f.rlib(fileline.o)(.debug_frame+0x6c): reloc against `.debug_frame': error 2
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: ld returned 1 exit status
```

**Comment by Manishearth** [comment]
IIRC the nightlies have some ubuntu problems

**Comment by aidanhs** [comment]
Updated to latest nightly.

**Comment by Manishearth** [comment]
thanks!

**Pull request merged**
